spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
